apiVersion: apps/v1
kind: Deployment
metadata:
  name: novapay-api
spec:
   replicas: 2
   selector:
      matchLabels:
        app:  novapay-api
   template:
      metadata:
        labels:
           app: novapay-api
      spec:
        containers:
         - name: novapay-api
           image: yadavshrikrishna65/novapay-api:1.4-arm64
           imagePullPolicy: Always
           ports:
             - containerPort: 8080
           env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
               configMapKeyRef:
                 name: novapay-config
                 key: SPRING_DATASOURCE_URL


            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
               secretKeyRef:
                    name: postgres-secret
                    key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
               secretKeyRef:
                     name: postgres-secret
                     key: password
     
           readinessProbe:
               httpGet:
                 path: /api/health
                 port: 8080
               initialDelaySeconds: 10
               periodSeconds: 5

           livenessProbe:
               httpGet:
                 path: /api/health
                 port: 8080
               initialDelaySeconds: 20
               periodSeconds: 10

           resources:
              requests:
               cpu: "100m"
               memory: "256Mi"
              limits:
               cpu: "500m"
               memory: "512Mi"
