apiVersion: apps/v1
kind: Deployment
metadata:
  name: novapay-api
spec:
   replicas: 1
   selector:
      matchLabels:
        app:  novapay-api
   template:
      metadata:
        labels:
           app: novapay-api
      spec:
        containers:
         - name: novapay-api
           image: yadavshrikrishna65/novapay-api:1.4-arm64
           imagePullPolicy: Always
           ports:
             - containerPort: 8080
           env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/novapay_db

            - name: SPRING_DATASOURCE_USERNAME
              value: novapay

            - name: SPRING_DATASOURCE_PASSWORD
              value: novapay_dev 
